Gin n Tonic Kotlin front page  ADD
JoeyKraemer/drinkMaster pull request #2
Opened 2023-05-16 08:08 UTC by HakanEgeOzerol

2023-05-16 10:26 UTC, JoeyKraemer requested changes, later dismissed
Please review your code for code conventions,  in a lot of different files there is the empty line at the end missing

2023-05-16 21:22 UTC, AlvesBernardo requested changes

2023-05-16 21:22 UTC, AlvesBernardo commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer
tab the text in

2023-05-16 21:22 UTC, AlvesBernardo commented on app/src/main/res/layout/activity_main.xml
> +
empty lines to many

2023-05-16 21:22 UTC, AlvesBernardo requested changes

2023-05-16 21:22 UTC, AlvesBernardo commented on app/src/main/res/layout/activity_rum_coke.xml
empty lines 2 you usually do 1

2023-05-16 21:22 UTC, AlvesBernardo commented on app/src/main/res/layout/activity_rum_coke.xml
> +
here there are 3

2023-05-16 21:22 UTC, AlvesBernardo commented on app/src/main/res/layout/activity_rum_coke.xml
> +        android:text="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer
tab text in

2023-05-17 09:07 UTC, AlvesBernardo approved these changes

2023-05-17 09:08 UTC, merged