V2
JoeyKraemer/drinkMaster pull request #4
Opened 2023-05-24 22:10 UTC by AlvesBernardo

Cricitcal merge issues fixes. 
Pop Up animation
Pop up stlyle

2023-05-25 12:53 UTC, JoeyKraemer requested changes

2023-05-25 12:53 UTC, JoeyKraemer commented on app/src/main/java/com/example/tileandbackground/MainActivity.kt
delete empty lines

2023-05-25 12:53 UTC, JoeyKraemer commented on app/src/main/java/com/example/tileandbackground/MainActivity.kt
> +
delete empty line

2023-05-25 12:53 UTC, JoeyKraemer commented on app/src/main/java/com/example/tileandbackground/MainActivity.kt
> +    }
indentation is wrong

2023-05-25 12:53 UTC, JoeyKraemer commented on app/src/main/java/com/example/tileandbackground/MainActivity.kt
> +
delete empty line

2023-05-25 12:53 UTC, JoeyKraemer commented on app/src/main/java/com/example/tileandbackground/MainActivity.kt
delete one empty line

2023-05-25 12:53 UTC, JoeyKraemer commented on app/src/main/java/com/example/tileandbackground/Rum_coke.kt
> +
delete empty line

2023-05-25 12:53 UTC, JoeyKraemer commented on app/src/main/res/layout/activity_main.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
add empty line at the end

2023-05-25 12:53 UTC, JoeyKraemer commented on app/src/main/res/layout/pop_up.xml
> +</LinearLayout>
add empty line at the end

2023-06-08 10:52 UTC, JoeyKraemer requested changes
Please fix the pointed out styling mistakes

2023-06-08 10:52 UTC, JoeyKraemer commented on app/build.gradle
>  }
empty line

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +
two empty lines

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +
rm empty line

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +        /*
delete commented code

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +        //setContentView(R.layout.)
commented code

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +
empty line

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +        /*
rm comments

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +        // sets the image to the imageview from our itemHolder class
indentation

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +       // holder.image. = ItemsViewModel.getImage()
commented code

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +}
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/ItemsViewModel.kt
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/ItemsViewModel.kt
> +}
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/ItemsViewModel.kt
> +
rm line

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/MainActivity.kt
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/MainActivity.kt
> +        /*
rm commented code

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/MainActivity.kt
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/MainActivity.kt
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/MainActivity.kt
> +
rm line

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/MainActivity.kt
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/MainActivity.kt
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/readRequest.kt
> +}
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/sendRequest.kt
> +}
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/sendRequest.kt
> +
rm line

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/layout/activity_main.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
still not changed

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/layout/activity_rum_coke.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/layout/gin_tonic.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/layout/gintonic.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/layout/layout_recycler.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/layout/ok_box.xml
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/layout/ok_box.xml
>  </LinearLayout>
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/layout/pop_up.xml
> +</LinearLayout>
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/layout/recycler_view.xml
> +
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/layout/recycler_view.xml
> +        </FrameLayout>
rm ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
>  </adaptive-icon>
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
>  </adaptive-icon>
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/values/ic_launcher_background.xml
> +</resources>
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/values/strings.xml
> +
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on app/src/main/res/values/themes.xml
>  </resources>
add ln

2023-06-08 10:52 UTC, JoeyKraemer commented on build.gradle
>  }
add ln

2023-06-08 11:42 UTC, AlvesBernardo commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +        //setContentView(R.layout.)
Yohan will need them for later

2023-06-09 07:38 UTC, JoeyKraemer approved these changes

2023-06-09 07:38 UTC, merged