Finished the admin page, finished pop up page and made some changhes on te ok page
JoeyKraemer/drinkMaster pull request #5
Opened 2023-06-08 09:25 UTC by CadarIustin

2023-06-08 11:33 UTC, JoeyKraemer requested changes

2023-06-08 11:33 UTC, JoeyKraemer commented on app/src/main/res/layout/admin_panel.xml
> +
remove line

2023-06-08 11:33 UTC, JoeyKraemer commented on app/src/main/res/layout/admin_panel.xml
> +</LinearLayout>
add empty line

2023-06-08 11:33 UTC, JoeyKraemer commented on app/src/main/res/layout/finished_box.xml
>  </LinearLayout>
add empty line

2023-06-08 11:33 UTC, JoeyKraemer commented on app/src/main/res/layout/ok_box.xml
>  </LinearLayout>
add empty line

2023-06-08 11:56 UTC, AlvesBernardo requested changes

2023-06-08 11:56 UTC, AlvesBernardo commented on app/src/main/res/layout/admin_panel.xml
> -
delete empty line

2023-06-08 11:57 UTC, AlvesBernardo requested changes
Look at how the other are made this wont work

2023-06-09 07:56 UTC, JoeyKraemer approved these changes

2023-06-09 07:56 UTC, JoeyKraemer commented on app/src/main/res/drawable/border.xml
> +</shape>
add empty line

2023-06-13 09:34 UTC, JoeyKraemer reviewed
LGTM!

2023-06-14 08:15 UTC, AlvesBernardo requested changes

2023-06-14 08:15 UTC, AlvesBernardo commented on app/src/main/res/layout/finished_box.xml
>  </LinearLayout>
add empty line at the end

2023-06-19 13:01 UTC, AlvesBernardo requested changes

2023-06-19 13:01 UTC, AlvesBernardo commented on app/src/main/res/layout/ok_box.xml
delete empty lines

2023-06-19 13:01 UTC, AlvesBernardo commented on app/src/main/res/layout/admin_panel.xml
> +
THIS NEEDS TO BE FIXED TODAY. CLEAR IDS

2023-06-20 08:14 UTC, AlvesBernardo requested changes
Constraint not connected check error message
https://developer.android.com/develop/ui/views/layout/constraint-layout

2023-06-22 23:26 UTC, AlvesBernardo commented
Final version of Frontend finished merged to backend already.
For the main branch ONLY merge Backend do not merge FRONTNED

2023-06-23 15:00 UTC, merged