Final version Backend
JoeyKraemer/drinkMaster pull request #6
Opened 2023-06-12 09:01 UTC by HakanEgeOzerol

2023-06-13 09:48 UTC, JoeyKraemer requested changes
Please people. DO your coding style right. 

 I am begging

2023-06-13 09:48 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +    // text watcher for the pinCode popup
use spaces not tabs

2023-06-13 09:48 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +
rm ln

2023-06-13 09:48 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +
rm ln !

2023-06-13 09:48 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +
rm ln!

2023-06-13 09:48 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/ItemsViewModel.kt
> +
rm ln!

2023-06-13 09:48 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/OnOrderButtonPress.kt
> +    fun onPress(): Void;
rm ln
add empty line

2023-06-13 09:48 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/SendRequest.kt
> +}
add empty line

2023-06-13 09:48 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/SendRequest.kt
> +}
@YohanLoz

2023-06-13 09:48 UTC, JoeyKraemer commented on app/src/main/res/drawable/graph.xml
> +</layer-list>
add empty line

2023-06-13 09:48 UTC, JoeyKraemer commented on app/src/main/res/drawable/graphbar.xml
> +</layer-list>
add empty line

2023-06-13 09:48 UTC, JoeyKraemer commented on app/src/main/res/layout/activity_admin.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
add empty line

2023-06-13 09:48 UTC, JoeyKraemer commented on app/src/main/res/layout/pincode_pop_up.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
add empty line

2023-06-14 08:13 UTC, AlvesBernardo submitted a review, later dismissed

2023-06-14 08:13 UTC, AlvesBernardo commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
delete empty lines

2023-06-14 08:13 UTC, AlvesBernardo commented on app/src/main/java/com/example/ProjectDrinkMaster/MainActivity.kt
delete double empty lines

2023-06-14 08:13 UTC, AlvesBernardo commented on app/src/main/java/com/example/ProjectDrinkMaster/MainActivity.kt
same here

2023-06-14 08:13 UTC, AlvesBernardo commented on app/src/main/java/com/example/ProjectDrinkMaster/MainActivity.kt
>      private fun prepareDiffernetDrinks() {
needs explaination on this function?

2023-06-23 07:50 UTC, JoeyKraemer requested changes

2023-06-23 07:50 UTC, JoeyKraemer commented on README.md
> +Backend: Bernardo, Yohan and Joey
Mention first name and last name and make it a bit more professional. 

This project will look good on your future portfolio

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +    val graphHeight = 600
?

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +        // createErrorBox(text)
rm comment

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +        override fun afterTextChanged(s: Editable?) {
136-177 make it pretty

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/AdminActivity.kt
> +    /*fun createErrorBox(errorMsg: String?) {
rm comment

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +}
add empty line

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/DrinksActivity.kt
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/DrinksActivity.kt
> +}
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/DrinksActivity.kt
> +
rm ln 2x

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/EditDrinksActivity.kt
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/EditDrinksActivity.kt
> +
rm ln 5x

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/EditDrinksActivity.kt
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/EditDrinksActivity.kt
> +}
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/OnOrderButtonPress.kt
> +}
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/OnSnapPostitionChangerListener.kt
> +}
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/ProgressBar.kt
> +}
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/SendRequest.kt
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/SendRequest.kt
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/SendRequest.kt
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/SendRequest.kt
> +}
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/java/com/example/ProjectDrinkMaster/readRequest.kt
> +}
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/drawable/restart.xml
> +</vector>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/activity_drinks.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/activity_admin.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/activity_drinks.xml
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/activity_edit_drinks.xml
> +</ScrollView>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/activity_main.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/edit_drinks_descriptions.xml
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/edit_drinks_descriptions.xml
> +</LinearLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/edit_drinks_descriptions.xml
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/edit_drinks_ingredients.xml
> +
rm ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/edit_drinks_ingredients.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/edit_drinks_names.xml
> +</LinearLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/edit_drinks_title.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/error_box.xml
> +</LinearLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/finished_box.xml
> +</LinearLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/layout_recycler.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/ok_box.xml
> +</LinearLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/pincode_pop_up.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/receipt_pop_up.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/layout/recycler_view.xml
> +</RelativeLayout>
add empty ln

2023-06-23 07:50 UTC, JoeyKraemer commented on app/src/main/res/values/colors.xml
>  </resources>
add empty ln

2023-06-23 08:02 UTC, AlvesBernardo commented on app/src/main/java/com/example/ProjectDrinkMaster/CustomAdapter.kt
> +
there is no empty line

2023-06-23 14:59 UTC, JoeyKraemer approved these changes

2023-06-23 15:00 UTC, merged